server:
  port: 9000

spring:
  datasource:
    password: 123
    username: root
    url: jdbc:mysql://192.168.88.133:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.88.133:8848
  application:
    name: gulimall-member
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.cwy.gulimall.product.entity
  global-config:
    db-config:
      id-type: auto